export { WEAPONS, WEAPON_ORDER } from './definitions'
export { weaponState } from './weaponState'
export { WeaponView } from './WeaponView'
export { fireWeapon } from './combat'
export type { WeaponId, WeaponDef, WeaponHudSnapshot } from './types'
